---
title: "NY NOAA Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(p8105.datasets)
library(wesanderson)

data("ny_noaa")

noaa_df =
  ny_noaa %>% 
  slice_sample(n = 100000) %>% 
 separate(date, c("year","month","day")) %>% 
  mutate(
    year = as.factor(year),
    month = as.factor(month),
    day = as.factor(day),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin)
  ) %>% 
  mutate(
    prcp = round(prcp * .03937 / 10),
    tmax = (tmax / 10),
    tmin = (tmin / 10),
    snow = round(snow * .03937),
    snwd = round(snwd * .03937)
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
noaa_df %>% 
  na.omit() %>% 
  filter(snow > 5) %>% 
plot_ly(y = ~snow, color = ~year, type = "box" )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
noaa_df %>% 
  na.omit() %>% 
  plot_ly(y = ~tmax, x = ~tmin, type = "scatter", mode = "markers", color = ~month, alpha = 0.5)
```

### Chart C

```{r}

```

