---
title: "Dashboard"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: simplex
---



Dashboard page!!

```{r}
library(tidyverse)
library(plotly)
library(p8105.datasets)

```

```{r}
data("ny_noaa")
```


```{r}
noaa_df =
  ny_noaa %>% 
  slice_sample(n = 100000) %>% 
 separate(date, c("year","month","day")) %>% 
  mutate(
    year = as.factor(year),
    month = as.factor(month),
    day = as.factor(day),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin)
  ) %>% 
  mutate(
    prcp = round(prcp * .03937 / 10),
    tmax = ((tmax / 10) * 1.8) + 32 ,
    tmin = ((tmin / 10) * 1.8) + 32,
    snow = round(snow * .03937),
    snwd = round(snwd * .03937)
  )
  
```


This graph is looking at the general trends of snowfall of at least 5 and at most 50 inches over the years. 
```{r}
noaa_df %>% 
  na.omit() %>% 
  filter(snow > 5 & snow < 50) %>% 
plot_ly(y = ~snow, color = ~year, type = "box", colors = "viridis")
```


This graph is a comparison of the maximum and minimum temperatures, which can be furthers specified based on the month of the year.
```{r}
noaa_df %>% 
  na.omit() %>% 
  plot_ly(y = ~tmax, x = ~tmin, type = "scatter", mode = "markers", color = ~month, alpha = 0.5, colors = "viridis")
```


This graph is a look at snow accumulation over the years. This can be further specified based on the station ID.
```{r}
noaa_df %>%
  na.omit() %>% 
  filter(snwd > 0) %>% 
   plot_ly(y = ~snwd, x = ~year, type = "bar", color = ~id, colors = "viridis")
```

