---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(p8105.datasets)
library(flexdashboard)

noaa_df =
  ny_noaa %>% 
  slice_sample(n = 100000) %>% 
 separate(date, c("year","month","day")) %>% 
  mutate(
    year = as.factor(year),
    month = as.factor(month),
    day = as.factor(day),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin)
  ) %>% 
  mutate(
    prcp = round(prcp * .03937 / 10),
    tmax = ((tmax / 10) * 1.8) + 32 ,
    tmin = ((tmin / 10) * 1.8) + 32,
    snow = round(snow * .03937),
    snwd = round(snwd * .03937)
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Snowfall General Trends in inches, specified by year

```{r}
noaa_df %>% 
  na.omit() %>% 
  filter(snow > 5 & snow < 50) %>% 
plot_ly(y = ~snow, color = ~year, type = "box", colors = "viridis") 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Maximum Temperatures vs Minimum Temperatures in Fahrenheit, specified by month

```{r}
noaa_df %>% 
  na.omit() %>% 
  plot_ly(y = ~tmax, x = ~tmin, type = "scatter", mode = "markers", color = ~month, alpha = 0.5, colors = "viridis")
```

### Snow Accumulation in inches, specified by station

```{r}
noaa_df %>%
  na.omit() %>% 
  filter(snwd > 0) %>% 
   plot_ly(y = ~snwd, x = ~year, type = "bar", color = ~id, colors = "viridis") %>% 
  layout(
    scene = list(
      yaxis = list(title = "Snow fall in inches"),
      xaxis = list(title = "Year")
    )
  )
```

